### ISSUE TITLE
Handover a domain while installing

### ISSUE THREAD

**Issue by bloarbgames** [timetheoretical/jitsi-meet-outlook#4] opened 2020-04-28 07:31 UTC
Since not every user is able to find the configuration items in Outlook him/herself to declare a Jitsi domain, it would be usefull if the domain can be set while executing the MSI.

**Comment by gillesdubois** [comment] 2020-04-28 11:35
Hi @bloarbgames, 

I think the issue you opened is similar to mine : https://github.com/timetheoretical/jitsi-meet-outlook/issues/2

Regards,
Gilles Dubois.

**Comment by timetheoretical** [comment] 2020-04-28 16:06
Indeed, I am closing this as it is a duplicate of #2. It seems like many might stand to benefit from such a feature.

**Closed by timetheoretical** 2020-04-28 16:06 UTC
Labels: duplicate
