### ISSUE TITLE
Some problems after installation

### ISSUE THREAD

**Issue by DirkHeinke** [timetheoretical/jitsi-meet-outlook#10] opened 2020-05-15 09:28 UTC
Hi,

I just installed the plugin but either I did something completely wrong during installation or its partly broken for me. Perhaps someone can guide me, how to debug and find the root of the issues? Here are my problems:
1. Changing the ID, does not update the URL.
![image](https://user-images.githubusercontent.com/5230945/82032638-d112f800-969b-11ea-9a8a-c66cb721131b.png)
2. Clicking on "Random ID" is not doing anything.
3. If I create a new appointment with right click, the jitsi Extension is not show (only when I create the meeting with the new extension button.

Thanks
Dirk

**Comment by timetheoretical** [comment] 2020-05-16 14:30
Strange. As to 1-2: it sounds like there is a disconnect between the appointment ribbon group and the appointment item. Does the ID field turn up blank when you create a new Jitsi Meet appointment, or does it match the RoomID that is displayed in the url in the body of the appointment item?

What version of the plug-in are you using, and what version of Outlook?

3. It is by design that the Jitsi Meet appointment ribbon only is displayed if you create a new appointment from the "New Jitsi Meet" button. However, I'll look into whether "New Jitsi Meet" item can appear in the right-click menu of the calendar tab.

**Comment by DirkHeinke** [comment] 2020-05-18 09:58
The ID and the URL have the same content in the beginning. 
Im using Outlook 2016 (16.0.5005.1000) 32-bit and installed `JitsiMeetOutlook-v0.4.0-windows-x86.msi`

3. I think I didn't explained it right:
Clicking here:
![image](https://user-images.githubusercontent.com/5230945/82199841-87761780-98fe-11ea-83b9-7906b9bdb1c8.png)
Shows the Jitsi meet Option
![image](https://user-images.githubusercontent.com/5230945/82199872-9361d980-98fe-11ea-980e-2a4299228a5a.png)
But clicking here:
![image](https://user-images.githubusercontent.com/5230945/82199990-bb513d00-98fe-11ea-8079-9aca272bd7c5.png)
does not:
![image](https://user-images.githubusercontent.com/5230945/82200027-c7d59580-98fe-11ea-8926-14a9c698808a.png)

**Comment by timetheoretical** [comment] 2020-06-04 17:51
I have tried to repackage the installer as "AnyCPU"; did that resolve your issue with buttons not working?

As for 3. that behaviour is expected. It's designed that way to avoid issues with updating the URL via regex that could be introduced by the user if the text is not already there in the right format when a new appointment is created. Do you see any practical issues with this?

**Comment by DirkHeinke** [comment] 2020-06-05 08:28
I tried to install the 0.5 but it fails with this error:
![image](https://user-images.githubusercontent.com/5230945/83854592-38f6b480-a717-11ea-875a-7cdbaf00db20.png)
Are you aware of the additional requirement? If yes, I'll download it later and test.

**Comment by timetheoretical** [comment] 2020-06-05 09:06
Yes, as you can see from [Microsoft's pages](https://docs.microsoft.com/en-us/visualstudio/vsto/how-to-install-the-visual-studio-tools-for-office-runtime-redistributable?view=vs-2019), the VSTO runtime is a requirement to run add-ons created in that framework (such as this one).

If that is not installed on your computer, it could very well explain the issues you are facing.

I noticed that the link that is provided in the warning message refers to an older version of the runtime. For the latest I could find, please see [here](https://www.microsoft.com/en-us/download/details.aspx?id=56961).

**Comment by DirkHeinke** [comment] 2020-06-05 09:41
Okay. I installed it with success. but the problems are still the same. Is there any way I can debug it? I have VisualStudio installed, but never done anything with outlook extensions/plugins.

**Comment by timetheoretical** [comment] 2020-06-05 09:56
I see. Good to hear that you got past the check at install-time at least.

For a starter you could clone the project, open it in Visual Studio (the .sln file) and then try and build the plugin yourself by clicking the button in the screenshot below:
![vs_debug](https://user-images.githubusercontent.com/56090670/83863356-254d4d00-a71b-11ea-84b2-7f749cc67199.png)

**Comment by timetheoretical** [comment] 2020-10-06 19:10
Closing this as nobody else have reported the same issue.

**Closed** 2020-10-06 19:10 UTC
Labels: bug

**Comment by DirkHeinke** [comment] 2020-10-13 19:06
Sorry I had no time for further testing and the most colleagues are using other tools. Anyways thank you very much for your support and good luck with this project :)
